### ISSUE TITLE
Widget shows oldest/first space, but not the recent one

### ISSUE THREAD

**Issue by blu-IT** [Basster/humhub-modules-recent-spaces#7]
Hello,

I updated the module from v. 0.4 to v.0.5 after the old version crashed my dashboard (HumHub v. 1.12.1).
Now everything works fine again, but the "recent spaces" widget does not show the recent spaces, but begins with the first/oldest space.
Clicking on the list it shows exact the order the spaces where created. But recent woukld mean to show the reverse order of spaces and the "youngest" space on top.

Could you please fix this? Thanks!

**Comment by Basster** [comment]
Version [0.5.1](https://github.com/Basster/humhub-modules-recent-spaces/releases/tag/0.5.1) should fix it.

Sorry, I don't have any humhub instance running anymore, so this bundle is more or less abandoned. Maybe @ArchBlood or @luke- feel comfortable to continue maintaining this module?

**Comment by blu-IT** [comment]
Works! 

Thanks for the quick reaction & support!!!

**Comment by ArchBlood** [comment]
I don't mind doing so
